### ISSUE TITLE
Update philologic URLs

### ISSUE THREAD

**Issue by pasqLisena** [Odeuropa/knowledge-graph#3]
With the update of philologic, URLs such as

    https://artflsrv03.uchicago.edu/philologic4/newberryfrc1217/navigate/28921/1/

should be changed into

    https://artflsrv04.uchicago.edu/philologic4.7/newberryfrc1217/navigate/28921/1/

**Comment by rtroncy** [comment]
Starting from https://odeuropa.tools.eurecom.fr/texts/1176b240-3b17-55fb-ac20-fd226eb32752 ... I understand that the source will soon be updated so that https://artflsrv03.uchicago.edu/philologic4/newberryfrc1217/navigate/28921/1/ is actually transformed into https://artflsrv04.uchicago.edu/philologic4.7/newberryfrc1217/navigate/28921/1/ ... but for the various excerpt, I'm wondering if we could also not link to the original pages, e.g. Excerpt 1 will be linked to https://archive.org/details/courierdupas00unse/page/1197/mode/2up?view=theater. Is it worth it? Too much work?

**Comment by pasqLisena** [comment]
Sorry @rtroncy , I thought I had replied.

I think it is too much work because we did not take note of the page during crawling.
If you think that we have a real use case, we may re-crawl things.
But honestly, it is so convenient to go to the full text, search the snippet, click on the link that they provide, which I don't really see the point.

Update: not all of these links passed to artflsrv04, I am doing a manual selection
